[package]
name = "ha-ndarray"
version = "0.5.0"
edition = "2021"
authors = ["code@tinychain.net"]
description = "A hardware-accelerated n-dimensional array"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/TinyChain-Inc/ha-ndarray.git"

keywords = ["ndarray", "tensor", "gpu", "ml", "parallel"]
categories = ["data-structures", "hardware-support", "mathematics"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
all = ["complex", "freqfs", "opencl", "stream"]
complex = ["num-complex", "rustfft"]
debug_crash = [] # enable this to panic rather than retuning an error when debugging
freqfs = ["freqfs/stream", "stream"]
opencl = ["memoize", "ocl"]
stream = ["destream", "futures"]
wasm = ["wasm-bindgen"]

[dependencies]
destream = { path = "../destream", version = "0.10.1", optional = true }
futures = { version = "0.3", optional = true }
frand = "0.10"
freqfs = { path = "../freqfs", version = "0.13", optional = true }
get-size = "0.1"
lazy_static = "1.5"
memoize = { version = "0.5", optional = true }
num-complex = { version = "0.4", optional = true }
number-general = { path = "../number-general", version = "0.14" }
num_cpus = "1.16"
ocl = { version = "0.19", optional = true }
rayon = "1.10"
rustfft = { version = "6.2", optional = true }
safecast = "0.2"
smallvec = "1.13"
transpose = "0.2"
wasm-bindgen = { version = "0.2", optional = true }
